/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as EvenementsIndexRouteImport } from './routes/evenements/index'
import { Route as EvenementsSlugRouteImport } from './routes/evenements/$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminEvenementsIndexRouteImport } from './routes/_authenticated/admin/evenements/index'
import { Route as AuthenticatedAdminEvenementsIdRouteImport } from './routes/_authenticated/admin/evenements/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EvenementsIndexRoute = EvenementsIndexRouteImport.update({
  id: '/evenements/',
  path: '/evenements/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsSlugRoute = EvenementsSlugRouteImport.update({
  id: '/evenements/$slug',
  path: '/evenements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminEvenementsIndexRoute =
  AuthenticatedAdminEvenementsIndexRouteImport.update({
    id: '/evenements/',
    path: '/evenements/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEvenementsIdRoute =
  AuthenticatedAdminEvenementsIdRouteImport.update({
    id: '/evenements/$id',
    path: '/evenements/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/evenements/$slug': typeof EvenementsSlugRoute
  '/evenements/': typeof EvenementsIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/evenements/$id': typeof AuthenticatedAdminEvenementsIdRoute
  '/admin/evenements/': typeof AuthenticatedAdminEvenementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/evenements/$slug': typeof EvenementsSlugRoute
  '/evenements': typeof EvenementsIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/evenements/$id': typeof AuthenticatedAdminEvenementsIdRoute
  '/admin/evenements': typeof AuthenticatedAdminEvenementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/evenements/$slug': typeof EvenementsSlugRoute
  '/evenements/': typeof EvenementsIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/evenements/$id': typeof AuthenticatedAdminEvenementsIdRoute
  '/_authenticated/admin/evenements/': typeof AuthenticatedAdminEvenementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/categories'
    | '/admin'
    | '/evenements/$slug'
    | '/evenements/'
    | '/admin/'
    | '/admin/evenements/$id'
    | '/admin/evenements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/categories'
    | '/evenements/$slug'
    | '/evenements'
    | '/admin'
    | '/admin/evenements/$id'
    | '/admin/evenements'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/auth'
    | '/categories'
    | '/_authenticated/admin'
    | '/evenements/$slug'
    | '/evenements/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/evenements/$id'
    | '/_authenticated/admin/evenements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  EvenementsSlugRoute: typeof EvenementsSlugRoute
  EvenementsIndexRoute: typeof EvenementsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/evenements/': {
      id: '/evenements/'
      path: '/evenements'
      fullPath: '/evenements/'
      preLoaderRoute: typeof EvenementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements/$slug': {
      id: '/evenements/$slug'
      path: '/evenements/$slug'
      fullPath: '/evenements/$slug'
      preLoaderRoute: typeof EvenementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/evenements/': {
      id: '/_authenticated/admin/evenements/'
      path: '/evenements'
      fullPath: '/admin/evenements/'
      preLoaderRoute: typeof AuthenticatedAdminEvenementsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/evenements/$id': {
      id: '/_authenticated/admin/evenements/$id'
      path: '/evenements/$id'
      fullPath: '/admin/evenements/$id'
      preLoaderRoute: typeof AuthenticatedAdminEvenementsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEvenementsIdRoute: typeof AuthenticatedAdminEvenementsIdRoute
  AuthenticatedAdminEvenementsIndexRoute: typeof AuthenticatedAdminEvenementsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminEvenementsIdRoute: AuthenticatedAdminEvenementsIdRoute,
    AuthenticatedAdminEvenementsIndexRoute:
      AuthenticatedAdminEvenementsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  EvenementsSlugRoute: EvenementsSlugRoute,
  EvenementsIndexRoute: EvenementsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
